name: Test Kubectl Secret
on:
  push:
    branches: [ "main" ]

env: 
  TEST_NAME_SPACE: e-dekont-test

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Setup kubectl
      uses: azure/setup-kubectl@v4
      with:
        version: 'latest'
      id: install
    - name: Set kube context
      uses: azure/k8s-set-context@v4
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.CLUSTER_ADMIN_CONFIG }}
    - name: Get kubernetes pods
      run: |
        echo "kubectl get po -n ${{ inputs.deploy_name_space }}"

