
name: Call a reusable workflow test-backend
on:
  push:
    branches: [ "main" ]

jobs:
  call-workflow-in-github-devops-actions:
    uses: finvelox-devops-test/github-devops-actions/test-frontend.yaml@main
