
name: Call a reusable workflow test-backend
on:
  push:
    branches: [ "main" ]

env:
  DEPLOY_NAME_SPACE: default

jobs:
  print:
    runs-on: ubuntu-latest
    outputs:
      deploy_name_space: ${{ steps.step1.outputs.deploy_name_space }}
    steps:
      - name: Print env to outputs
        id: step1
        run: |
          echo "deploy_name_space: $DEPLOY_NAME_SPACE"
          echo "deploy_name_space=$DEPLOY_NAME_SPACE" >> $GITHUB_OUTPUT

  call-workflow-in-github-devops-actions:
    needs:
      - print
    uses: finvelox-devops-test/github-devops-actions/.github/workflows/test-frontend.yaml@main
    with:
      deploy_name_space: ${{ needs.print.outputs.deploy_name_space }}
    secrets: 
      kubeconfig: ${{ secrets.TEST }}




