
name: Call a reusable workflow test-backend
on:
  push:
    branches: [ "main" ]

env:
  DEPLOY_NAME_SPACE: e-dekont-test


jobs:
  call-workflow-in-github-devops-actions:
    uses: finvelox-devops-test/github-devops-actions/.github/workflows/test-frontend.yaml@main
