name: Call a reusable workflow test-backend
on:
  push:
    branches: [ "main"  ]

  jobs:
    test-backend:
      permissions:
        contents: read
        pull-request: write
      uses: finvelox-devops-test/github-devops-actions/.github/workflows/test-backend.yaml@v1
      with:
        config-path: .github/labeler.yml
      secrets:
        token: ${{ secrets.GITHUB_TOKEN }}
