
name: Call a reusable workflow test-backend
on:
  push:
    branches: [ "main" ]

jobs:
  call-workflow-passing-data:
    permissions:
      contents: read
      pull-request: write
    uses: finvelox-devops-test/github-devops-actions/.github/workflows/test-backend.yaml@main
    with:
      config-path: .github/labeler.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
